name: Build Expo APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g eas-cli
          npm install

      - name: Login to Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build Android APK
        run: eas build -p android --profile preview --non-interactive --wait

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: RedSeaFishFinder-APK
          path: dist/**
          
